###############################################################
# BEHAVIOUR CLASSIFICATION AND TIME-BUDGET QUANTIFICATION
# -------------------------------------------------------------
# This script reads the simulated chicken keypoint data produced
# by SimulaKeypointTracking.R, builds a feature matrix, trains
# a Random Forest classifier, and quantifies the time the
# chicken spends in each behavioural category.
#
# The script proceeds as follows:
#   1. Read the full simulated dataset from CSV.
#   2. Select the motion features relevant for classification.
#   3. Z-score-normalize all features so that the classifier
#      treats each feature on equal footing regardless of its
#      physical units or scale.
#   4. Train a Random Forest with 300 trees to predict the
#      behavioural state label for each video frame.
#   5. Use the trained model to predict behaviours across all
#      frames and compute how many minutes the chicken spent
#      in each behaviour.
#   6. Save the feature dataset and a bar-chart PNG of the
#      estimated time budget.
#
# Input file (must exist in the working directory):
#   - chicken_simulated_data_full.csv  (produced by SimulaKeypointTracking.R)
#
# Output files written to the working directory:
#   - chicken_features_for_classification.csv : normalized feature
#     matrix with behavioural labels (used to train the model)
#   - behaviour_time_budget.png : bar chart of minutes per behaviour
###############################################################

library(dplyr)        # data manipulation (select, %>%)
library(randomForest) # Random Forest classifier

# Frames per second of the original video (must match SimulaKeypointTracking.R)
fps <- 10

###############################################################
# 1. READ SIMULATED DATA
###############################################################

# Load the full dataset generated by SimulaKeypointTracking.R.
# This CSV contains one row per video frame with raw keypoint
# positions, behavioural labels, and all derived motion features.
data <- read.csv("chicken_simulated_data_full.csv", stringsAsFactors = FALSE)

###############################################################
# 2. FEATURE MATRIX
###############################################################

# Select the subset of columns that will be used as predictors.
# These ten features capture the key aspects of chicken movement:
#   vel_body        – speed of the body (neck keypoint) between frames
#   dist_body_20    – total body displacement over the last ~2 seconds
#   dist_body_50    – total body displacement over the last ~5 seconds
#   parallel        – head displacement component along the body axis
#   perpendicular   – head displacement component perpendicular to the body
#   angle_var       – variance of the head-body angle over the last ~2 seconds
#   acc_head        – frame-to-frame acceleration of the head
#   head_length     – Euclidean length of the head vector (neck → head)
#   vel_head        – speed of the head keypoint between frames
#   ratio_head_body – ratio of head speed to body speed
features <- data %>%
  select(
    vel_body, dist_body_20, dist_body_50,
    parallel, perpendicular, angle_var,
    acc_head, head_length, vel_head, ratio_head_body
  )

###############################################################
# 3. NORMALIZE FEATURES
###############################################################

# Apply z-score normalization (zero mean, unit variance) to all features.
# This is important because:
#   - Features are measured in different units and on different scales.
#   - Without normalization, features with large absolute values could
#     dominate the model even if they carry less information.
# scale() centers each column by subtracting its mean and then divides
# by its standard deviation, producing a matrix of standardized values.
features_scaled <- scale(features)

# Combine the normalized features with the behavioural label column.
# na.omit() removes any rows that contain NA values introduced by the
# rolling-window computations at the edges of the time series.
dataset <- data.frame(features_scaled, state = data$state)
dataset  <- na.omit(dataset)

# Save the normalized feature dataset so that the exact training data
# can be inspected or reused without re-running the simulation.
write.csv(dataset, "chicken_features_for_classification.csv", row.names = FALSE)

###############################################################
# 4. TRAIN RANDOM FOREST CLASSIFIER
###############################################################

# Convert 'state' to a factor so that randomForest() treats the
# problem as classification rather than regression.
# If 'state' were left as a character vector, R might mishandle it
# and the model would attempt to predict numeric values.
dataset$state <- as.factor(dataset$state)

# Train the Random Forest classifier:
#   state ~ . : predict 'state' using all other columns as features
#   ntree = 300 : grow 300 decision trees; more trees give more stable
#                 predictions at the cost of additional computation time
model <- randomForest(state ~ ., data = dataset, ntree = 300)

###############################################################
# 5. PREDICT BEHAVIOURS
###############################################################

# Apply the trained Random Forest model to every frame in the dataset.
# predict() returns a factor vector with one predicted behaviour label
# per row (i.e. per video frame).
predicted <- predict(model, dataset)

###############################################################
# 6. TIME SPENT IN EACH BEHAVIOUR
###############################################################

# Count the number of frames assigned to each predicted behaviour.
# table() tallies occurrences of each factor level in 'predicted'.
frame_counts <- table(predicted)

# Convert frame counts to minutes:
#   frames / fps = seconds spent in that behaviour
#   seconds / 60 = minutes spent in that behaviour
minutes_per_behaviour <- frame_counts / fps / 60

# Print the time budget so results are visible in the console / log
print(minutes_per_behaviour)

###############################################################
# 7. VISUALISE RESULTS
###############################################################

# Save a bar chart of the estimated time budget as a PNG file.
# The chart shows how many minutes the chicken spent in each behaviour
# according to the Random Forest predictions.
png(filename = "behaviour_time_budget.png", width = 800, height = 600)

barplot(
  minutes_per_behaviour,
  col  = "steelblue",             # fill colour for the bars
  ylab = "Minutes",               # Y-axis label
  main = "Estimated behavioural time budget"  # chart title
)

dev.off()  # close the graphics device and write the PNG file to disk

message("ClassifBehaviour.R completed successfully.")
message("Outputs saved to:")
message("  chicken_features_for_classification.csv")
message("  behaviour_time_budget.png")
